Python 3 POCL:
  script: |
    export PY_EXE=python3
    export PYOPENCL_TEST=portable:pthread
    # cython is here because pytential (for now, for TS) depends on it
    export EXTRA_INSTALL="pybind11 cython numpy mako mpi4py oct2py"
    curl -L -O https://gitlab.tiker.net/inducer/ci-support/raw/main/build-and-test-py-project.sh
    . ./build-and-test-py-project.sh
  tags:
  - python3
  - pocl
  - mpi
  except:
  - tags
  artifacts:
    reports:
      junit: test/pytest.xml

Python 3 Nvidia Titan V:
  script: |
    export PY_EXE=python3
    export PYOPENCL_TEST=nvi:titan
    export EXTRA_INSTALL="pybind11 cython numpy mako oct2py"
    # cython is here because pytential (for now, for TS) depends on it
    curl -L -O https://gitlab.tiker.net/inducer/ci-support/raw/main/build-and-test-py-project.sh
    . ./build-and-test-py-project.sh
  tags:
  - python3
  - nvidia-titan-v
  except:
  - tags
  artifacts:
    reports:
      junit: test/pytest.xml

Python 3 POCL Examples:
  script:
  - test -n "$SKIP_EXAMPLES" && exit
  - export PY_EXE=python3
  - export PYOPENCL_TEST=portable:pthread
  - export EXTRA_INSTALL="pybind11 numpy mako"
  - curl -L -O https://gitlab.tiker.net/inducer/ci-support/raw/main/build-py-project-and-run-examples.sh
  - ". ./build-py-project-and-run-examples.sh"
  tags:
  - python3
  - pocl
  - large-node
  except:
  - tags

Python 3 Conda:
  script: |
    curl -L -O https://gitlab.tiker.net/inducer/ci-support/raw/main/build-and-test-py-project-within-miniconda.sh
    . ./build-and-test-py-project-within-miniconda.sh
  tags:
  # - docker-runner
  - linux
  - large-node
  except:
  - tags

Documentation:
  script: |
    EXTRA_INSTALL="pybind11 cython numpy"
    curl -L -O https://gitlab.tiker.net/inducer/ci-support/raw/main/build-docs.sh
    CI_SUPPORT_SPHINX_VERSION_SPECIFIER=">=4.0"
    . ./build-docs.sh
  tags:
  - python3

Flake8:
  script:
  - curl -L -O https://gitlab.tiker.net/inducer/ci-support/raw/main/prepare-and-run-flake8.sh
  - . ./prepare-and-run-flake8.sh "$CI_PROJECT_NAME" test examples
  tags:
  - python3
  except:
  - tags

Pylint:
  script: |
    export PY_EXE=python3
    EXTRA_INSTALL="pybind11 numpy mako"
    curl -L -O https://gitlab.tiker.net/inducer/ci-support/raw/master/prepare-and-run-pylint.sh
    . ./prepare-and-run-pylint.sh "$CI_PROJECT_NAME" examples/*.py test/test_*.py
  tags:
  - python3
  except:
  - tags

Mypy:
  script: |
    curl -L -O https://tiker.net/ci-support-v0
    . ./ci-support-v0
    build_py_project_in_venv
    python -m pip install mypy
    ./run-mypy.sh
  tags:
  - python3
  except:
  - tags
