name: test-conda-env
channels:
- conda-forge
- nodefaults

dependencies:
- python=3
- git
- libhwloc=2
- numpy
# pocl 3.1 required for full SVM functionality
- pocl>=3.1
- mako
- pyopencl
- islpy
- pip
- jax
